name: adcom
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.2.11+69

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  syncfusion_flutter_calendar: ^19.1.59
  camera: ^0.9.4+5
  intl: ^0.17.0
  provider: ^5.0.0
  syncfusion_flutter_core: ^19.1.69
  path_provider: ^2.0.2
  path: ^1.8.0
  image_picker: ^0.8.0+3
  shared_preferences: ^2.0.6
  http: ^0.13.3
  filter_list: ^0.0.9
  onesignal_flutter: ^3.2.7
  firebase_messaging: ^10.0.2
  firebase_core: ^1.3.0
  cupertino_stepper: ^0.2.0
  glyphicon: ^0.2.2
  data_connection_checker_tv: ^0.3.5-nullsafety
  
  fl_paging: ^2.0.0
  flutter_staggered_animations: ^1.0.0
  url_launcher: ^6.0.9
  pdf: ^3.4.2
  open_file: ^3.2.1
  syncfusion_flutter_pdfviewer: ^19.2.47-beta
  fluttertoast: ^8.0.7
  gradient_widgets: ^0.6.0
  flutter_onboard: ^1.0.3
  im_stepper: ^0.1.3
  pull_to_refresh: ^2.0.0
  rename: ^1.3.1
  printing: ^5.4.3
  dio: ^4.0.0
  lint: ^1.0.0
  badges: ^2.0.1
  file_picker: ^4.0.1
  external_path: ^1.0.1
  permission_handler: ^8.1.4+2
  flutter_downloader: ^1.7.0
  connectivity_plus: ^1.1.0
  grouped_list: ^4.1.0
  loader_overlay: ^2.0.2+1
  flutter_spinkit: ^5.1.0
  flutter_phone_direct_caller: ^2.1.0
  transparent_image: ^2.0.0
  bloc: ^7.2.1
  photo_view: ^0.13.0
  flutter_weather_bg_null_safety: ^1.0.0
  ringtone_player: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.1"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/iconLauncher2.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-LightItalic.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf  
          
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
